services:

  traefik:
    image: traefik:latest
    ports:
      - 80:80
    volumes:
      - $GHOST_HOME/traefik.yml:/etc/traefik/traefik.yml
      - $GHOST_HOME/dynamic.yml:/etc/traefik/dynamic.yml
    command:
      - --configFile=/etc/traefik/traefik.yml
